// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';

// Insurance policies
export const REQUEST_INSURANCE_POLICIES = 'REQUEST_INSURANCE_POLICIES';
export const RECEIVE_INSURANCE_POLICIES = 'RECEIVE_INSURANCE_POLICIES';
export const ERROR_INSURANCE_POLICIES = 'ERROR_INSURANCE_POLICIES';

export const REQUEST_INSURANCE_POLICY = 'REQUEST_INSURANCE_POLICY';
export const RECEIVE_INSURANCE_POLICY = 'RECEIVE_INSURANCE_POLICY';
export const ERROR_INSURANCE_POLICY = 'ERROR_INSURANCE_POLICY';

export const REQUEST_CREATE_INSURANCE_POLICY = 'REQUEST_CREATE_INSURANCE_POLICY';
export const SUCCESS_CREATE_INSURANCE_POLICY = 'SUCCESS_CREATE_INSURANCE_POLICY';
export const ERROR_CREATE_INSURANCE_POLICY = 'ERROR_CREATE_INSURANCE_POLICY';

export const REQUEST_UPDATE_INSURANCE_POLICY = 'REQUEST_UPDATE_INSURANCE_POLICY';
export const SUCCESS_UPDATE_INSURANCE_POLICY = 'SUCCESS_UPDATE_INSURANCE_POLICY';
export const ERROR_UPDATE_INSURANCE_POLICY = 'ERROR_UPDATE_INSURANCE_POLICY';

export const REQUEST_DELETE_INSURANCE_POLICY = 'REQUEST_DELETE_INSURANCE_POLICY';
export const SUCCESS_DELETE_INSURANCE_POLICY = 'SUCCESS_DELETE_INSURANCE_POLICY';
export const ERROR_DELETE_INSURANCE_POLICY = 'ERROR_DELETE_INSURANCE_POLICY';

export const SET_INSURANCE_POLICIES_FILTERS = 'SET_INSURANCE_POLICIES_FILTERS';
export const SET_INSURANCE_POLICIES_PAGINATION = 'SET_INSURANCE_POLICIES_PAGINATION';

// Client
export const REQUEST_CLIENTS = 'REQUEST_CLIENTS';
export const RECEIVE_CLIENTS = 'RECEIVE_CLIENTS';
export const ERROR_CLIENTS = 'ERROR_CLIENTS';

export const REQUEST_CLIENT = 'REQUEST_CLIENT';
export const RECEIVE_CLIENT = 'RECEIVE_CLIENT';
export const ERROR_CLIENT = 'ERROR_CLIENT';

export const REQUEST_CREATE_CLIENT = 'REQUEST_CREATE_CLIENT';
export const SUCCESS_CREATE_CLIENT = 'SUCCESS_CREATE_CLIENT';
export const ERROR_CREATE_CLIENT = 'ERROR_CREATE_CLIENT';

export const REQUEST_UPDATE_CLIENT = 'REQUEST_UPDATE_CLIENT';
export const SUCCESS_UPDATE_CLIENT = 'SUCCESS_UPDATE_CLIENT';
export const ERROR_UPDATE_CLIENT = 'ERROR_UPDATE_CLIENT';

export const REQUEST_DELETE_CLIENT = 'REQUEST_DELETE_CLIENT';
export const SUCCESS_DELETE_CLIENT = 'SUCCESS_DELETE_CLIENT';
export const ERROR_DELETE_CLIENT = 'ERROR_DELETE_CLIENT';

export const SET_CLIENTS_FILTERS = 'SET_CLIENTS_FILTERS';
export const SET_CLIENTS_PAGINATION = 'SET_CLIENTS_PAGINATION';